import { defineArrayMember, defineField, defineType } from "sanity";
import { FeaturedThumbnailInput } from "../components/featured-thumbnail-input";

const categories = ["DOCUMENTARY", "COMMERCIAL", "NARRATIVE", "LYRICAL"];

export const projectType = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "overview", title: "Overview", default: true },
    { name: "ordering", title: "Ordering" },
    { name: "media", title: "Media" },
    { name: "credits", title: "Credits" },
  ],
  fields: [
    defineField({ name: "title", title: "Title", type: "string", group: "overview", validation: (rule) => rule.required() }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "overview",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "year",
      title: "Legacy year",
      type: "number",
      group: "overview",
      hidden: true,
      readOnly: true,
      validation: (rule) => rule.integer().min(1900).max(2100),
    }),
    defineField({
      name: "projectType",
      title: "Project type",
      type: "string",
      description: "Display label such as Short Film, Documentary, Brand Film, or Campaign.",
      group: "overview",
    }),
    defineField({
      name: "cinematographyRole",
      title: "Your cinematography role",
      type: "string",
      description: "Use Additional Cinematography when you contributed photography but were not the principal cinematographer.",
      group: "overview",
      initialValue: "directorOfPhotography",
      options: {
        layout: "radio",
        list: [
          { title: "Director of Photography", value: "directorOfPhotography" },
          { title: "Additional Cinematography", value: "additionalCinematography" },
        ],
      },
    }),
    defineField({
      name: "thumbnailSubheading",
      title: "Work thumbnail subheading",
      type: "string",
      description: "Optional. A short distinction such as Streaming on Netflix or Sundance Winner.",
      group: "overview",
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: "thumbnailThirdLine",
      title: "Work thumbnail third line",
      type: "string",
      description: "Optional. A third line of context shown beneath the thumbnail subheading.",
      group: "overview",
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "string" })],
      options: { list: categories.map((category) => ({ title: category, value: category })) },
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: "showOnFrontPage",
      title: "Show on front page",
      type: "boolean",
      description: "Include this project in the opening Selected Work list.",
      group: "overview",
      initialValue: false,
    }),
    defineField({
      name: "publishOnSite",
      title: "Publish on public site",
      type: "boolean",
      description: "Turn this off to keep the project in your private library without showing it publicly.",
      group: "overview",
      initialValue: true,
    }),
    defineField({
      name: "frontPageOrder",
      title: "Front page order",
      type: "number",
      description: "Lower numbers appear first in the opening Selected Work list.",
      group: "ordering",
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      description: "Include this project in the Featured category within the Work section.",
      group: "overview",
      initialValue: false,
    }),
    defineField({
      name: "featuredOrder",
      title: "Featured order",
      type: "number",
      description: "Lower numbers appear first in the Featured category.",
      group: "ordering",
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "commercialOrder",
      title: "Commercial order",
      type: "number",
      description: "Lower numbers appear first in the Commercial category.",
      group: "ordering",
      hidden: ({ document }) => !Array.isArray(document?.categories) || !document.categories.includes("COMMERCIAL"),
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "documentaryOrder",
      title: "Documentary order",
      type: "number",
      description: "Lower numbers appear first in the Documentary category.",
      group: "ordering",
      hidden: ({ document }) => !Array.isArray(document?.categories) || !document.categories.includes("DOCUMENTARY"),
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "narrativeOrder",
      title: "Narrative order",
      type: "number",
      description: "Lower numbers appear first in the Narrative category.",
      group: "ordering",
      hidden: ({ document }) => !Array.isArray(document?.categories) || !document.categories.includes("NARRATIVE"),
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "homepageOrder",
      title: "Legacy homepage order",
      type: "number",
      group: "overview",
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: "thumbnail",
      title: "Work thumbnail",
      type: "image",
      description: "Shown in Work. Use the Featured 2.5:1 preview to check the wide crop and 16:9 for category grids.",
      group: "media",
      components: { input: FeaturedThumbnailInput },
      options: {
        hotspot: {
          previews: [
            { title: "3:4", aspectRatio: 3 / 4 },
            { title: "Square", aspectRatio: 1 },
            { title: "16:9", aspectRatio: 16 / 9 },
            { title: "Featured 2.5:1", aspectRatio: 2.5 },
            { title: "Panorama", aspectRatio: 4 },
          ],
        },
      },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
          description: "Optional. Describe the image for visitors using assistive technology.",
        }),
      ],
    }),
    defineField({
      name: "homepageImage",
      title: "Home screen image",
      type: "image",
      description: "Shown full bleed on the opening screen. Keep important subjects within a crop-safe central area.",
      group: "media",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
          description: "Optional. Describe the image for visitors using assistive technology.",
        }),
      ],
    }),
    defineField({
      name: "videos",
      title: "Project videos",
      type: "array",
      description: "Add one or more spots. Drag items to set the order they appear on the project page.",
      group: "media",
      of: [
        defineArrayMember({
          name: "projectMuxVideo",
          title: "Video",
          type: "object",
          fields: [
            defineField({
              name: "title",
              title: "Spot title",
              type: "string",
              description: "Optional. For example: Launch, Anthem, or Spot 1.",
            }),
            defineField({
              name: "muxVideo",
              title: "Mux video",
              type: "mux.video",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "poster",
              title: "Custom video thumbnail",
              type: "image",
              description: "Optional. Upload an image to replace the thumbnail generated from the video timecode.",
              options: { hotspot: true },
            }),
          ],
          preview: {
            select: { title: "title", muxMedia: "muxVideo.asset", poster: "poster" },
            prepare: ({ title, muxMedia, poster }) => ({ title: title || "Untitled spot", media: poster || muxMedia }),
          },
        }),
      ],
    }),
    defineField({
      name: "muxVideo",
      title: "Legacy single video",
      type: "mux.video",
      description: "Existing single video. New videos should be added to Project videos above.",
      group: "media",
      readOnly: true,
      hidden: ({ value }) => !value,
    }),
    defineField({
      name: "enableHoverPreview",
      title: "Enable hover preview",
      type: "boolean",
      description: "Play a muted thumbnail preview on supported desktop devices.",
      group: "media",
      initialValue: false,
    }),
    defineField({
      name: "hoverPreviewStartTime",
      title: "Preview start time",
      type: "number",
      description: "Time in seconds where the thumbnail preview should begin.",
      group: "media",
      hidden: ({ parent }) => !parent?.enableHoverPreview,
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: "video",
      title: "Legacy video configuration",
      type: "projectVideo",
      description: "Preserved from the pre-Mux schema. Replace it with the Video field above when ready.",
      group: "media",
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: "gallery",
      title: "Project stills",
      type: "array",
      group: "media",
      description: "Drag multiple image files onto this field to upload a batch. Drag items to reorder them.",
      of: [
        defineArrayMember({
          name: "galleryImage",
          title: "Still image",
          type: "image",
          fields: [
            defineField({
              name: "alt",
              title: "Alternative text",
              type: "string",
              description: "Optional. Describe the image for visitors using assistive technology.",
            }),
            defineField({
              name: "presentation",
              title: "Presentation width",
              type: "string",
              initialValue: "wide",
              options: {
                layout: "radio",
                list: [
                  { title: "Wide", value: "wide" },
                  { title: "Standard", value: "standard" },
                  { title: "Portrait", value: "portrait" },
                ],
              },
            }),
            defineField({
              name: "order",
              title: "Order",
              type: "number",
              description: "Lower numbers appear first. Array order breaks ties.",
              validation: (rule) => rule.integer().min(0),
            }),
          ],
        }),
        // Keep the original object member readable while existing documents are migrated naturally.
        defineArrayMember({ type: "projectStill" }),
      ],
    }),
    defineField({ name: "director", title: "Director", type: "string", group: "credits" }),
    defineField({ name: "productionCompany", title: "Production company", type: "string", group: "credits" }),
    defineField({ name: "description", title: "Description", type: "text", rows: 4, group: "credits" }),
    defineField({ name: "credits", title: "Additional credits", type: "array", group: "credits", of: [defineArrayMember({ type: "credit" })] }),
  ],
  orderings: [
    { title: "Front page order", name: "frontPageOrderAsc", by: [{ field: "frontPageOrder", direction: "asc" }] },
    { title: "Featured order", name: "featuredOrderAsc", by: [{ field: "featuredOrder", direction: "asc" }] },
    { title: "Commercial order", name: "commercialOrderAsc", by: [{ field: "commercialOrder", direction: "asc" }] },
    { title: "Documentary order", name: "documentaryOrderAsc", by: [{ field: "documentaryOrder", direction: "asc" }] },
    { title: "Narrative order", name: "narrativeOrderAsc", by: [{ field: "narrativeOrder", direction: "asc" }] },
  ],
  preview: { select: { title: "title", subtitle: "projectType", media: "thumbnail" } },
});
