import { defineArrayMember, defineField, defineType } from "sanity";

const categories = ["DOCUMENTARY", "COMMERCIAL", "NARRATIVE", "LYRICAL"];

export const projectType = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "overview", title: "Overview", default: true },
    { name: "media", title: "Media" },
    { name: "credits", title: "Credits" },
  ],
  fields: [
    defineField({ name: "title", title: "Title", type: "string", group: "overview", validation: (rule) => rule.required() }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "overview",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "number",
      group: "overview",
      validation: (rule) => rule.integer().min(1900).max(2100),
    }),
    defineField({
      name: "projectType",
      title: "Project type",
      type: "string",
      description: "Display label such as Short Film, Documentary, Brand Film, or Campaign.",
      group: "overview",
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "string" })],
      options: { list: categories.map((category) => ({ title: category, value: category })) },
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: "showOnFrontPage",
      title: "Show on front page",
      type: "boolean",
      description: "Include this project in the opening Selected Work list.",
      group: "overview",
      initialValue: false,
    }),
    defineField({
      name: "frontPageOrder",
      title: "Front page order",
      type: "number",
      description: "Lower numbers appear first in the opening Selected Work list.",
      group: "overview",
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      description: "Include this project in the Featured category within the Work section.",
      group: "overview",
      initialValue: false,
    }),
    defineField({
      name: "featuredOrder",
      title: "Featured order",
      type: "number",
      description: "Lower numbers appear first in the Featured category.",
      group: "overview",
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "homepageOrder",
      title: "Legacy homepage order",
      type: "number",
      group: "overview",
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: "thumbnail",
      title: "Thumbnail / splash image",
      type: "image",
      group: "media",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
          description: "Optional. Describe the image for visitors using assistive technology.",
        }),
      ],
    }),
    defineField({
      name: "muxVideo",
      title: "Video",
      type: "mux.video",
      description: "Optional. Upload a video to Mux or choose an existing Mux asset.",
      group: "media",
    }),
    defineField({
      name: "video",
      title: "Legacy video configuration",
      type: "projectVideo",
      description: "Preserved from the pre-Mux schema. Replace it with the Video field above when ready.",
      group: "media",
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: "gallery",
      title: "Project stills",
      type: "array",
      group: "media",
      description: "Drag multiple image files onto this field to upload a batch. Drag items to reorder them.",
      of: [
        defineArrayMember({
          name: "galleryImage",
          title: "Still image",
          type: "image",
          fields: [
            defineField({
              name: "alt",
              title: "Alternative text",
              type: "string",
              description: "Optional. Describe the image for visitors using assistive technology.",
            }),
            defineField({
              name: "presentation",
              title: "Presentation width",
              type: "string",
              initialValue: "wide",
              options: {
                layout: "radio",
                list: [
                  { title: "Wide", value: "wide" },
                  { title: "Standard", value: "standard" },
                  { title: "Portrait", value: "portrait" },
                ],
              },
            }),
            defineField({
              name: "order",
              title: "Order",
              type: "number",
              description: "Lower numbers appear first. Array order breaks ties.",
              validation: (rule) => rule.integer().min(0),
            }),
          ],
        }),
        // Keep the original object member readable while existing documents are migrated naturally.
        defineArrayMember({ type: "projectStill" }),
      ],
    }),
    defineField({ name: "director", title: "Director", type: "string", group: "credits" }),
    defineField({ name: "productionCompany", title: "Production company", type: "string", group: "credits" }),
    defineField({ name: "description", title: "Description", type: "text", rows: 4, group: "credits" }),
    defineField({ name: "credits", title: "Additional credits", type: "array", group: "credits", of: [defineArrayMember({ type: "credit" })] }),
  ],
  orderings: [
    { title: "Front page order", name: "frontPageOrderAsc", by: [{ field: "frontPageOrder", direction: "asc" }] },
    { title: "Featured order", name: "featuredOrderAsc", by: [{ field: "featuredOrder", direction: "asc" }] },
    { title: "Year, newest first", name: "yearDesc", by: [{ field: "year", direction: "desc" }] },
  ],
  preview: { select: { title: "title", subtitle: "projectType", media: "thumbnail" } },
});
